baseURL: "https://learning.peyet.ddns.net/"
title: "Guides"
languageCode: fr
defaultContentLanguage: fr

disableKinds:
  - taxonomy
  - term

module:
  imports:
    - path: github.com/gpeyet-learning/guides-theme

markup:
  highlight:
    noClasses: false
    codeFences: true
  tableOfContents:
    startLevel: 2
    endLevel: 3

params:
  description: "Bibliothèque de guides techniques."
